
	\item Barplot of null counts in raw data
<<barplotNullRaw,fig=TRUE, width=12, height=8>>=
# plot barplot of null counts by sample
barplotNull(target)
@

	\item Delete rows (genes) with only null counts
<<>>=
# delete unexpressed gene
target$counts <- deleteUnexpressedGene(target$counts)
@
	\item Barplot of total counts in raw counts
<<barplotTotalCountRaw, fig=TRUE, width=12, height=8>>=
barplotTotalCount(target)
@
	\item Boxplot of log2(raw counts + 1)
<<boxplotTotalCountRaw, fig=TRUE, width=12, height=8>>=
boxplotCounts(target)
@
	\item Density plot of log2(raw counts + 1)
<<densityPlotRaw,fig=TRUE, width=12, height=8>>=
densityplotRNA(target)
@
	\item{Save raw matrix}
<<rawMatrix>>=
saveCountMatrix(
		target$counts,
		# path of the file (do not omit the last "/")
		outPath,
		# file name
		paste("anaDiff_", projectName,"_rawCountMatrix.txt", sep="")
)
@
	\item Pool technical replicates
<<pool>>=	
poolCountTarget <- poolTechRep(target)
@
	\item Plot barplot of pooled counts
<<barplotTotalCountPool, fig=TRUE, width=12, height=8>>=
barplotTotalCount(poolCountTarget)
@
	\item Plot boxplot of pooled counts
<<boxplotPool, fig=TRUE, width=12, height=8>>=
boxplotCounts(poolCountTarget)
@
	\item Save pooled counts matrix
<<matrixPool>>=
saveCountMatrix(
		poolCountTarget$counts,
		# path of the file (do not omit the last "/")
		outPath,
		# file name
		paste("anaDiff_", projectName, "_rawPooledCountMatrix.txt", sep="")
)
@
	\item create countDataSet (DESeq object) with pooled matrix and estimate size factor 
<<cds>>=
countDataSet <- normDESeq(poolCountTarget$counts, poolCountTarget$condition)
# print size factors
print("Size factors : ", quote=F)
print(sizeFactors(countDataSet))
@
	\item Normalize count
<<norm>>=
normTarget <- normalizeTarget(poolCountTarget)
@
