
\section{Target creation}

<<targetCreation>>=
# create target list containing various objects use in the analysis
target <- buildTarget(
		sampleNames,
		projectName,
		fileNames,
		projectPath,
		repTechGroup,
		condition,
		exp
)

# sort target by condition
target <- sortTarget(target)
@

\section{Analysis}

	\subsection{Normalization}

\begin{itemize}
	\item Hierarchical clustering on raw data

<<clusterRaw,fig=TRUE, width=12, height=8>>=
# compute clustering on unormalized counts
repClust(target)
@

	\item Barplot of null counts in raw data
<<barplotNullRaw,fig=TRUE, width=12, height=8>>=
# plot barplot of null counts by sample
barplotNull(target)
@

	\item Delete rows (genes) with only null counts
<<>>=
# delete unexpressed gene
target$counts <- deleteUnexpressedGene(target$counts)
@
	\item Barplot of total counts in raw counts
<<barplotTotalCountRaw, fig=TRUE, width=12, height=8>>=
barplotTotalCount(target)
@
	\item Boxplot of log2(raw counts + 1)
<<boxplotTotalCountRaw, fig=TRUE, width=12, height=8>>=
boxplotCounts(target)
@
	\item Density plot of log2(raw counts + 1)
<<densityPlotRaw,fig=TRUE, width=12, height=8>>=
densityplotRNA(target)
@
	\item{Save raw matrix}
<<rawMatrix>>=
saveCountMatrix(
		target$counts,
		# path of the file (do not omit the last "/")
		outPath,
		# file name
		"rawCountMatrix.txt"
)
@
	\item Pool technical replicates
<<pool>>=	
poolCountTarget <- poolTechRep( target )
@
	\item Plot barplot of pooled counts
<<barplotTotalCountPool, fig=TRUE, width=12, height=8>>=
barplotTotalCount(poolCountTarget)
@
	\item Plot boxplot of pooled counts
<<boxplotPool, fig=TRUE, width=12, height=8>>=
boxplotCounts(poolCountTarget)
@
	\item Save pooled counts matrix
<<matrixPool>>=
saveCountMatrix(
		poolCountTarget$counts,
		# path of the file (do not omit the last "/")
		outPath,
		# file name
		"pooledRawCountMatrix.txt"
)
@
	\item create countDataSet (DESeq object) with pooled matrix and estimate size factor 
<<cds>>=
countDataSet <- normDESeq(poolCountTarget$counts, poolCountTarget$condition)
# print size factors
print("Size factors : ", quote=F)
print(sizeFactors(countDataSet))
@
	\item Normalize count
<<norm>>=
normTarget <- normalizeTarget(poolCountTarget)
@
	\item Compute clustering of normTarget biological replicates and plot dendrogram
<<clusterNorm, fig=TRUE, width=12, height=8>>= 
repClust(normTarget)
@
	\item Plot boxplot and densityplot of normalized counts
<<boxplotNorm, fig=TRUE, width=12, height=8>>=
boxplotCounts(normTarget)
@
<<densityPlotNorm, fig=TRUE, width=12, height=8>>=
densityplotRNA(normTarget)
@
	\item Save normalized matrix
<<matrixNorm>>=
saveCountMatrix(
		normTarget$counts,
		# file path
		outPath,
		# file name
		"normalizedPooledCountMatrix.txt"
)
@
